<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ITEM-S73641" name="TestCases.TC22_WorkFlowManagement" tests="1" failures="0" timestamp="16 Mar 2021 20:05:30 GMT" time="79.113" errors="1">
  <testcase name="TC22_WorkFlowManagement1" time="79.113" classname="TestCases.TC22_WorkFlowManagement">
    <error type="junit.framework.AssertionFailedError" message="Error while clicking on element ://aw-tab-container[@class=&#039;ng-star-inserted&#039;]//h4[contains(text(),&#039;Assignement of the Target status&#039;)]//..//..//..//tbody/tr[contains(.,&#039;Loaded&#039;)]//p-checkbox">
      <![CDATA[junit.framework.AssertionFailedError: Error while clicking on element ://aw-tab-container[@class='ng-star-inserted']//h4[contains(text(),'Assignement of the Target status')]//..//..//..//tbody/tr[contains(.,'Loaded')]//p-checkbox
	at junit.framework.Assert.fail(Assert.java:47)
	at base.BaseTest.click(BaseTest.java:184)
	at PageObjects.WorkFlowManagement.WorkFlowEdittxtValidation(WorkFlowManagement.java:295)
	at TestCases.TC22_WorkFlowManagement.TC22_WorkFlowManagement1(TC22_WorkFlowManagement.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- TC22_WorkFlowManagement1 -->
</testsuite> <!-- TestCases.TC22_WorkFlowManagement -->
